export default [
    { ID: 'Sys000000', En: 'Function not Exist', Cn: '此功能不存在' },
    { ID: 'Front000000', En: 'Require Data Error', Cn: '请求数据出错' },
    { ID: 'Front000001', En: 'Require Login', Cn: '此功能要求登陆' },
    { ID: 'Validation000000', En: 'Validation code is incorrect.', Cn: '验证码错误' },
    { ID: 'SMS000001', En: 'Sending SMS error.', Cn: '手机短信发送，网络错误' },
    { ID: 'SMS000002', En: 'Sending SMS error.', Cn: '手机短信发送错误' },
    { ID: 'SMS000021', En: 'CallNumber CountryCode, callNumberValidCode is empty', Cn: '参数错误' },
    { ID: 'SMS000022', En: 'ValidationCode ValidationCodeUID is empty', Cn: '请填写验证码' },
    { ID: 'SMS000023', En: 'CallNumber Validation code is incorrect.', Cn: '手机验证码错误' },
    { ID: 'SMS000024', En: 'CallNumber Validation code is incorrect.', Cn: '手机验证码错误' },
    // 通用数据错误提示
    { ID: 'Common000001', En: 'Application List Empty', Cn: '应用列表为空' }, // Act: Application_GetList
    { ID: 'Common000002', En: 'Technique List Empty', Cn: '技术列表为空' }, // Act: Technique_GetList
    // 前台：NV命令取数据时返的身份验证有问题
    { ID: 'FUser000001', En: 'Time out, please login again.', Cn: '身份验证出错，或已超时，或在别的地方登录，请重新登录' },
    // login登陆页面
    { ID: 'User000070', En: 'Account, Email, Pwd or Validation Code is empty.', Cn: '帐户、密码、验证码不能为空' },
    { ID: 'User000071', En: 'The Account and Password do not match. Please try again.', Cn: '没有此帐户, 或密码错误' },
    { ID: 'User000072', En: 'This Account is limited.', Cn: '此帐户禁止登录' },
    { ID: 'User000073', En: 'this account is not activiated by Email, please check email and activiate', Cn: '此帐户尚未通过邮件击活，不能登录' },
    { ID: 'User000074', En: 'Wrong cell number', Cn: '电话号码错误' },
    //Signup前台
    { ID: 'FSignup000001', En: 'Validation Code has been sent, please check your SMS', Cn: '验证验已发送，请注意查询短信' },
    { ID: 'FSignup000002', En: 'Cell verified, please continue your registration.', Cn: '手机验证成功，请继续注册' },
    // Signup登陆页面
    { ID: 'User000060', En: 'Password or Email or FirstName or LastName Field or Validation Code is empty', Cn: '请填写所有带*号必填项' },
    { ID: 'User000061', En: 'Incorrect Email Format.', Cn: '邮箱格式不对' },
    { ID: 'User000062', En: 'This email has been used.', Cn: '邮箱已被使用' },
    { ID: 'User000063', En: 'Cell Number Error.', Cn: '手机验证参数错' },
    { ID: 'User000064', En: 'Cell Number Error.', Cn: '手机验证参数错' },
    { ID: 'User000065', En: 'Applying User Role, need the lab Account.', Cn: '申请User帐号，需提交Lab ID' },
    { ID: 'User000066', En: 'Lab Account does not exist.', Cn: 'Lab ID 不存在' },
    { ID: 'User000067', En: 'This Invitation Code does not exist.', Cn: '邀请号正确' },
    { ID: 'User000068', En: 'This cell has been used.', Cn: '此手机号已被注册。' },
    { ID: 'User000069', En: 'System Error.', Cn: '系统出错，请联系管理员' },
    { ID: 'User000300', En: 'CallNumber or Validation Code is empty', Cn: '参数出错' },
    { ID: 'User000301', En: 'This cell has been used.', Cn: '此手机号已被使用。' },
    { ID: 'User000302', En: 'This cell is not exist.', Cn: '此手机号不存在。' },
    // Activiate account激活帐号页面
    { ID: 'User000740', En: 'There is no Activiation Code', Cn: '没有激活码' },
    { ID: 'User000741', En: 'Activiation Code is wrong', Cn: '错误激活码' },
    { ID: 'User000742', En: 'The Account has been activiated.', Cn: '此帐户已经是激活状态了' },
    { ID: 'User000743', En: 'System Error', Cn: '内部错误' },
    // News List 页面
    { ID: 'News000020', En: 'NewsIndex is not the value of "DateTime" or "DateTimeDesc" or "Clicks" or "ClicksDesc"', Cn: '排序参数出错' },
    { ID: 'News000021', En: 'NewsType is not Int type', Cn: '新闻类型非整数' },
    { ID: 'News000022', En: 'PageSize or PageNumber is not Int type', Cn: '页数类型非整数' },
    { ID: 'News000023', En: 'PageSize should be over 0.', Cn: '页码需大于0' },
    { ID: 'News000024', En: 'No Result.', Cn: '没有相关新闻' },
    // News 详情页面
    { ID: 'News000001', En: 'This UID News does not exist', Cn: '此新闻不存在。' },
    // 前台comments模块
    { ID: 'FComments000001', En: 'Please input your comments', Cn: '请填写您的评论' },
    { ID: 'FComments000002', En: 'Please input validation code', Cn: '请填写验证码' },
    // comments模块
    { ID: 'Comments000010', En: 'CommentType or ArticleUID or Comments or Validation Code is empty', Cn: '请填写评论和验证码' },
    { ID: 'Comments000011', En: 'CommentType is not integer.', Cn: '评论类型不是整数' },
    { ID: 'Comments000012', En: 'CommentType: 10:Library; 20:ResearchEx; 30:Activity; 40:Video;', Cn: '评论类型只有:10, 20, 30, 40' },
    { ID: 'Comments000014', En: 'ArticleUID does not exist.', Cn: '评论文章不存在' },

    // 前台Files模块
    { ID: 'FFiles000001', En: 'This file is available for user account', Cn: '此文件仅限User帐号可查看' },
    { ID: 'FFiles000002', En: 'This file is available for Lab account', Cn: '此文件仅限Lab帐号可查看' },
    { ID: 'FFiles000003', En: 'This file is available for user account', Cn: '此文件仅限User帐号可下载' },
    { ID: 'FFiles000004', En: 'This file is available for Lab account', Cn: '此文件仅限Lab帐号可下载' },

    // Library List 页面
    { ID: 'Library000090', En: 'LibraryIndex is not the value of \'DateTime\' or \'DateTimeDesc\' or \'Clicks\' or \'ClicksDesc\'', Cn: '排序参数错误' },
    { ID: 'Library000091', En: 'PageSize or PageNumber is not Int type', Cn: '页码与每页数量须为整数' },
    { ID: 'Library000092', En: 'PageSize should be over 0.', Cn: '每页数量须大于零' },
    { ID: 'Library000092', En: 'PageSize should be over 0.', Cn: '每页数量须大于零' },
    // Library 详情 页面
    { ID: 'Library000030', En: 'LibraryUID is empty.', Cn: '请输入LibraryUID' },
    { ID: 'Library000031', En: 'This UID Library does not exist', Cn: '这个文章不存在' },
    { ID: 'Library000100', En: 'FileUID is empty.', Cn: '请提交文件UID' },
    { ID: 'Library000101', En: 'File does not exist.', Cn: '文件不存在' },
    { ID: 'Library000102', En: 'no permission to get html', Cn: '没有权限在线查看' },
    { ID: 'Library000201', En: 'FileUID is empty.', Cn: '请提交文件UID' },
    { ID: 'Library000202', En: 'File does not exist.', Cn: '文件不存在' },
    { ID: 'Library000203', En: 'no permission to download', Cn: '没有权限下载' },
    // 前台Share(包括Favorite)模块
    { ID: 'FFavorites000000', En: 'Save successfully', Cn: '收藏成功' },
    { ID: 'FFavorites000001', En: 'Remove successfully', Cn: '成功取消' },
    { ID: 'FShare000001', En: 'Share successfully', Cn: '分享成功' },
    { ID: 'FShare000002', En: 'Share successfully', Cn: '分享成功' },
    { ID: 'FShare000003', En: 'Share successfully', Cn: '分享成功' },
    { ID: 'FShare000004', En: 'Share successfully', Cn: '分享成功' },
    { ID: 'FShare000005', En: 'Share successfully', Cn: '分享成功' },
    // Share(包括Favorite)模块
    { ID: 'Favorites000010', En: 'ArticleType or ArticleUID is empty', Cn: '请输入ArticleType和ArticleUID' },
    { ID: 'Favorites000011', En: 'ArticleType is not integer.', Cn: 'ArticleType不是一个整数' },
    { ID: 'Favorites000012', En: 'ArticleType: 10:Library; 20:ResearchEx; 30:Activity; 40:Video;', Cn: 'ArticleType类型：10:Library; 20:ResearchEx; 30:Activity; 40:Video;' },
    { ID: 'Favorites000013', En: 'ArticleType: 10:Library; 20:ResearchEx; 30:Activity; 40:Video;', Cn: 'ArticleType类型：10:Library; 20:ResearchEx; 30:Activity; 40:Video;' },
    { ID: 'Favorites000014', En: 'ArticleUID does not exist.', Cn: '此文章不存在' },
    { ID: 'Favorites000015', En: 'this ArticleUID is already favorite.', Cn: '此文章已收藏' },
    { ID: 'Favorites000020', En: 'ArticleType or ArticleUID is empty', Cn: '请输入ArticleType和ArticleUID' },
    { ID: 'Favorites000022', En: 'ArticleUID does not exist.', Cn: '此文章不存在' },
    { ID: 'Favorites000023', En: 'ArticleType: 10:Library; 20:ResearchEx; 30:Activity; 40:Video;', Cn: 'ArticleType类型：10:Library; 20:ResearchEx; 30:Activity; 40:Video;' },
    { ID: 'Favorites000100', En: 'ArticleType or ArticleUID is empty', Cn: '请输入ArticleType和ArticleUID' },
    { ID: 'Favorites000101', En: 'This Favorite does not exist', Cn: '这个收藏不存在' },
    { ID: 'ShareRecords000010', En: 'ArticleType or ArticleUID or ShareUrl or ShareMedia or MediaType is empty', Cn: '缺少参数' },
    { ID: 'ShareRecords000011', En: 'ArticleType is not integer.', Cn: 'ArticleType不是一个整数' },
    { ID: 'ShareRecords000012', En: 'ArticleType: 10:Library; 20:ResearchEx; 30:Activity; 40:Video;', Cn: 'ArticleType类型：10:Library; 20:ResearchEx; 30:Activity; 40:Video;' },
    { ID: 'ShareRecords000013', En: 'ArticleType: 10:Library; 20:ResearchEx; 30:Activity; 40:Video;', Cn: 'ArticleType类型：10:Library; 20:ResearchEx; 30:Activity; 40:Video;' },
    { ID: 'ShareRecords000014', En: 'ArticleUID does not exist.', Cn: '此文章不存在' },
    { ID: 'ShareRecords000017', En: 'MediaType is not integer.', Cn: 'MediaType不是一个整数' },
    { ID: 'ShareRecords000018', En: 'MediaType is valid: 0=Wechat，1=SinaWeibo，2=Linkedin，3=Facebook，4=Twitter', Cn: 'MediaType无效: 0=微信，1=新浪，2=领英，3=Facebook，4=Twitter' },
    { ID: 'ShareRecords000015', En: 'this ArticleUID has been shared.', Cn: '此文章已被分享' },
    { ID: 'ShareRecords000016', En: 'Share Record Error.', Cn: '内部错误' },
    // Event List 页面
    { ID: 'OpticalSchool000091', En: 'ActivityIndex is not the value of ActivityName or ActivityNameDesc or StartDate or StartDateDesc or EndDate or EndDateDesc or Clicks or ClicksDesc or Country or CountryDesc', Cn: '排序参数错误' },
    { ID: 'OpticalSchool000099', En: 'AreaType: 10:Country; 20:Province; 30:City', Cn: '地区参数错误' },
    { ID: 'OpticalSchool000092', En: 'StartDate is not a date string, format:2012-12-28', Cn: '开始日期错误' },
    { ID: 'OpticalSchool000093', En: 'EndDate is not a date string, format:2012-12-28', Cn: '结束日期错误' },
    { ID: 'OpticalSchool000094', En: 'ShowStatus is not integer.', Cn: '显示参数应为整数' },
    { ID: 'OpticalSchool000095', En: '10 for English; 20 for Chinese; 30 for All version', Cn: '显示参数错误' },
    { ID: 'OpticalSchool000096', En: 'PageSize or PageNumber is not Int type', Cn: '页数及个数错误' },
    { ID: 'OpticalSchool000097', En: 'PageSize should be over 0.', Cn: '页数及个数错误' },
    // Event 详情页面
    { ID: 'OpticalSchool000071', En: 'ActivityUID is empty', Cn: 'UID标识为空' },
    { ID: 'OpticalSchool000072', En: 'the record does not exist.', Cn: '这个活动不存在' },
    { ID: 'OpticalSchool000781', En: 'ActivityUID is empty.', Cn: 'UID标识为空' },
    { ID: 'OpticalSchool000782', En: 'ActivityUID does not exist.', Cn: '这个活动不存在' },
    { ID: 'OpticalSchool000783', En: 'this ActivityUID has been Surveied.', Cn: '已经参加过了' },
    { ID: 'OpticalSchool000784', En: 'Activity Survey Record Error.', Cn: '数据错误' },
    // ResearchEx List 页面
    { ID: 'OpticalSchool000290', En: 'ResearchExIndex is not the value of DateTime or DateTimeDesc or Clicks or ClicksDesc', Cn: '排序参数错误' },
    { ID: 'OpticalSchool000291', En: 'ResearchExType is not integer', Cn: '类型不为整数' },
    { ID: 'OpticalSchool000292', En: 'PageSize or PageNumber is not Int type', Cn: '页数及个数错误' },
    { ID: 'OpticalSchool000293', En: 'PageSize should be over 0.', Cn: '页数及个数错误' },
    // ResearchEx 详情页面
    { ID: 'OpticalSchool000230', En: 'ResearchExUID is empty.', Cn: 'UID标识为空' },
    { ID: 'OpticalSchool000231', En: 'This UID ResearchEx does not exist', Cn: '这个科研经验不存在' },
    // Video List 页面
    { ID: 'OpticalSchool000571', En: 'VideoIndex is not the value of DateTime or DateTimeDesc or VideoName or VideoNameDesc or Clicks or ClicksDesc', Cn: '排序参数错误' },
    { ID: 'OpticalSchool000572', En: 'PageSize or PageNumber is not Int type', Cn: '页数及个数错误' },
    { ID: 'OpticalSchool000573', En: 'PageSize should be over 0.', Cn: '页数及个数错误' },
    // Video 详情页面
    { ID: 'OpticalSchool000561', En: 'VideoUID is empty', Cn: 'UID标识为空' },
    { ID: 'OpticalSchool000562', En: 'the record does not exist.', Cn: '这个视频不存在' },
    // Collaboration List 页面
    { ID: 'Opportunity000051', En: 'ApplicationIndex is not the value of DateTime or DateTimeDesc or Points or PointsDesc', Cn: '排序参数错误' },
    { ID: 'Opportunity000052', En: 'PageSize or PageNumber is not Int type', Cn: '页数及个数错误' },
    { ID: 'Opportunity000053', En: 'PageSize should be over 0.', Cn: '页数及个数错误' },
    // Collaboration 详情页面
    { ID: 'Opportunity000042', En: 'This UID Application or the user is not the Collaboration Users does not exist', Cn: '不存在' },
    // Recruit List 页面
    { ID: 'Opportunity000251', En: 'JobReleaseIndex is not the value of CreatedDateTime or CreatedDateTimeDesc', Cn: '排序参数错误' },
    { ID: 'Opportunity000252', En: 'JobType is not integer', Cn: '类型不为整数' },
    { ID: 'Opportunity000253', En: 'PageSize or PageNumber is not Int type', Cn: '页数及个数错误' },
    { ID: 'Opportunity000254', En: 'PageSize should be over 0.', Cn: '页数及个数错误' },
    // Recruit 详情页面
    { ID: 'Opportunity000231', En: 'JobReleaseUID is empty.', Cn: '请提交UID' },
    { ID: 'Opportunity000232', En: 'the record does not exist or the record is not belong to the user.', Cn: '不存在' },
    // 前台3A left 左边详情
    { ID: 'F3ALeft000000', En: 'Only jpg/gif/png accepted.', Cn: '仅限jpg,gif, png' },
    { ID: 'F3ALeft000001', En: 'The maximum size is 1M', Cn: '文件不可超过1M' },
    { ID: 'F3ALeft000002', En: 'Image uploaded successfully', Cn: '头像上传成功' },
    // 3A left 左边详情
    { ID: 'User000201', En: 'This User does not exist', Cn: '用户不存在' },
    { ID: 'User000202', En: 'Only jpg/gif/png accepted', Cn: '仅限jpg,gif, png' },
    { ID: 'User000203', En: 'The maximum size is 1M', Cn: '文件不可超过1M' },
    { ID: 'User000204', En: 'the CityUID does not exist.', Cn: '城市不存在' },
    { ID: 'User000205', En: 'ApplicationUID does not exist.', Cn: 'application不存在' },
    { ID: 'User000206', En: 'TechniqueUID does not exist.', Cn: 'Technology不存在' },
    { ID: 'User000206', En: 'nothing to update.', Cn: '没有提交要更新的项' },
    { ID: 'User000207', En: 'Record Error..', Cn: '系统数据出错' },
    { ID: 'User000208', En: 'Incorrect Email Format.', Cn: '邮箱格式不对' },
    { ID: 'User000221', En: 'This UID User does not exist', Cn: '用户不存在' },
    // 前台3A Profile 详情页面,
    { ID: 'F3AProfile000000', En: 'Update Successfully.', Cn: '信息更新成功' },
    { ID: 'F3AProfile000001', En: 'Password Changed Successfully.', Cn: '密码更新成功' },
    { ID: 'F3AProfile000002', En: 'Apply User Account Successfully.', Cn: 'User帐号升级申请发送成功' },
    { ID: 'F3AProfile000003', En: 'Cancel User Account Successfully.', Cn: '退出User帐号成功' },
    { ID: 'F3AProfile000004', En: 'Verified Successfully.', Cn: '手机号码验证成功，请确认更换手机号码' },
    { ID: 'F3AProfile000005', En: 'Changed cell number Successfully.', Cn: '更换手机号码成功' },
    // 3A Profile 详情页面, GetUserInfo, UpdatedUserInfo跟 ‘3A left 左边详情’一样的。
    { ID: 'User000241', En: 'OldPwd or NewPwd is empty', Cn: '请提交旧，新密码' },
    { ID: 'User000242', En: 'This OldPwd is not correct.', Cn: '旧密码不正确' },
    { ID: 'User000261', En: 'You are not learning account, can not apply user account.', Cn: '只有Learning帐号才可申请' },
    { ID: 'User000262', En: 'LabAccount is empty', Cn: '请提交实验室帐户' },
    { ID: 'User000263', En: 'LabAccount does not exist.', Cn: '实验室ID不存在' },
    { ID: 'User000511', En: 'You are not User account or applying User, can not quit.', Cn: '不是user帐户或正在申请user,无法退出' },
    { ID: 'User000512', En: 'LabUID is empty', Cn: '实验室ID不存在' },
    { ID: 'User000513', En: 'This UID User is not the Lab\'s User.', Cn: '不是这个实验室的user' },
    { ID: 'User000601', En: 'This UID User is not exist', Cn: '用户不存在' },
    { ID: 'User000602', En: 'This UID User is not exist', Cn: '参数错误' },
    { ID: 'User000603', En: 'Call Number Error.', Cn: '手机号码错误' },
    { ID: 'User000604', En: 'Call Number Error.', Cn: '手机号码错误' },
    { ID: 'User000605', En: 'This cell has been used.', Cn: '手机号码已被使用，请改用其它手机号。' },
    // 前台3A PointClaimPublicationUpload 详情页面,
    { ID: 'F3APointClaimPublicationUpload000000', En: 'Only accept doc/docx/ppt/pptx/pdf.', Cn: '仅限word, ppt, pdf' },
    { ID: 'F3APointClaimPublicationUpload000001', En: 'The Maximum size is 20M.', Cn: '文件不可超过20M' },
    { ID: 'F3APointClaimPublicationUpload000002', En: 'Upload successfully.', Cn: '上传成功' },
    { ID: 'F3APointClaimPublicationUpload000003', En: 'upload a file, please', Cn: '请上传文件' },
    // 3A PointClaimPublicationUpload 详情页面,
    { ID: 'ClientDocuments000001', En: 'FilesUID is empty', Cn: 'FilesUID参数为空' },
    { ID: 'ClientDocuments000005', En: 'FilesUID has been used by someone', Cn: 'FilesUID已被使用' },
    { ID: 'ClientDocuments000006', En: 'FilesUID has been used by someone', Cn: 'FilesUID已被使用' },
    { ID: 'ClientDocuments000007', En: 'the document has be reviewed, can not update.', Cn: '此文已被审核通过，不能再做修改' },
    { ID: 'ClientDocuments000002', En: 'Filedata is empty or length is zero.', Cn: '没有文件上传' },
    { ID: 'ClientDocuments000003', En: 'only accept doc, docx, ppt, pptx, pdf.', Cn: '只能上传doc,docx, ppt, pptx, pdf' },
    { ID: 'ClientDocuments000004', En: 'Only accept doc/docx/ppt/pptx/pdf.', Cn: '仅限word, ppt, pdf' }, // 无法分析这个文档
    { ID: 'ClientDocuments000011', En: 'UID is empty', Cn: '请上传文件标识UID' },
    { ID: 'ClientDocuments000012', En: 'This File does not exist.', Cn: '文件不存在' },
    { ID: 'ClientDocuments000013', En: 'This files is not yours', Cn: '文件不属于您的，不能删除' },
    { ID: 'ClientDocuments000014', En: 'the document has be reviewed, can not delete the file.', Cn: '此文已被审核通过，不能再删除' },
    { ID: 'ClientDocuments000021', En: 'ApplicationUID or TechniqueUID or Title or FilesUID or DOI is empty', Cn: '上传参数出错' },
    { ID: 'ClientDocuments000022', En: 'ApplicationUID does not exist.', Cn: '对应Application不存在' },
    { ID: 'ClientDocuments000023', En: 'TechniqueUID does not exist.', Cn: '对应Technique不存在' },
    { ID: 'ClientDocuments000024', En: 'This FilesUID Has been used', Cn: '文件FilesUID已被使用' },
    { ID: 'ClientDocuments000025', En: 'Insert Record Error.', Cn: '内部数据错误' },
    { ID: 'ClientDocuments000026', En: 'only User, Lab Account can submit the Publication.', Cn: '只有user, Lab帐号才能上传Publication' },
    { ID: 'ClientDocuments000027', En: 'the Doi already exist, please try another.', Cn: '此DOI已存在，请再试其它。' },
    // 前台3A PointClaimPublicationInfo 详情页面,
    { ID: 'F3APointClaimPublicationInfo000001', En: 'Document updated successful.', Cn: '文档更新成功' },
    { ID: 'F3APointClaimPublicationInfo000002', En: 'Document deleted successful.', Cn: '文档删除成功' },
    // 3A PointClaimPublicationInfo 详情页面,
    { ID: 'ClientDocuments000031', En: 'ClientDocumentsUID is empty.', Cn: '请上传publication标识' },
    { ID: 'ClientDocuments000032', En: 'This ClientDocumentsUID does not exist', Cn: '此Publication不存在' },
    { ID: 'ClientDocuments000041', En: 'ClientDocumentsUID or ApplicationUID or TechniqueUID or Title or Description or DOI is empty', Cn: '上传参数出错' },
    { ID: 'ClientDocuments000042', En: 'This ClientDocumentsUID does not exist', Cn: '此Publication不存在' },
    { ID: 'ClientDocuments000043', En: 'ApplicationUID does not exist.', Cn: '对应Application不存在' },
    { ID: 'ClientDocuments000044', En: 'TechniqueUID does not exist.', Cn: '对应Technique不存在' },
    { ID: 'ClientDocuments000045', En: 'Update Record Error.', Cn: '内部数据错误' },
    { ID: 'ClientDocuments000046', En: 'the Doi already exist, please try another.', Cn: '此DOI已存在，请再试其它。' },
    { ID: 'ClientDocuments000051', En: 'ClientDocumentsUID is empty.', Cn: '请上传publication标识' },
    { ID: 'ClientDocuments000052', En: 'This ClientDocumentsUID does not exist', Cn: '此Publication不存在' },
    { ID: 'ClientDocuments000053', En: 'Delete Record Error.', Cn: '内部数据错误' },
    //前台 3A PointClaimPublication详情页面,
    { ID: 'F3APointClaimPublication001', En: 'You are now allowed to upload Publication', Cn: '不准允上传Publication' },
    // 3A PointClaimPublication详情页面,
    { ID: 'ClientDocuments000061', En: 'ClientDocumentsIndex is not the value of DateTime or DateTimeDesc or Title or TitleDesc.', Cn: '排序参数错误' },
    { ID: 'ClientDocuments000062', En: 'PageSize or PageNumber is not Int type', Cn: '页数及个数错误' },
    { ID: 'ClientDocuments000063', En: 'PageSize should be over 0.', Cn: '页数及个数错误' },
    // 前台3A PointClaimExperiment详情页面,
    { ID: 'F3APointClaimExperiment000001', En: 'only User Account can submit the Research Experience.', Cn: '只有User帐号才能分享' },
    // 前台3A PointClaimExperimentUpload 详情页面,
    { ID: 'F3APointClaimExperimentUpload000001', En: 'Experimental Tips shared Successfully', Cn: 'Experiment Tips分享成功' },
    // 3A PointClaimExperimentUpload 详情页面,
    { ID: 'OpticalSchool000229', En: 'only User Account can submit the Research Experience.', Cn: '只有User帐号才能分享' },
    { ID: 'OpticalSchool000220', En: 'ResearchExType, ApplicationUIDs or TechniqueUIDs or Title is empty.', Cn: '上传参数出错' },
    { ID: 'OpticalSchool000221', En: 'ResearchExType is not integer.', Cn: '分类参数应为整数' },
    { ID: 'OpticalSchool000223', En: 'ApplicationUID does not exist.', Cn: '对应Application不存在' },
    { ID: 'OpticalSchool000224', En: 'TechniqueUID does not exist.', Cn: '对应Technique不存在' },
    { ID: 'OpticalSchool000228', En: 'Insert Record Error.', Cn: '内部数据错误' },
    // 前台3A PointClaimExperimentInfo 详情页面,
    { ID: 'F3APointClaimExperimentInfo000001', En: 'Experimental Tips updated successful.', Cn: '更新成功' },
    { ID: 'F3APointClaimExperimentInfo000002', En: 'Experimental Tips deleted successful.', Cn: '删除成功' },
    // 3A PointClaimExperimentInfo 详情页面,部分与前面的Experimental面页相同,这里是update,delete部分
    { ID: 'OpticalSchool000240', En: 'ResearchExUID or ResearchExType or ApplicationUIDs or TechniqueUIDs or Title is empty.', Cn: '参数出错' },
    { ID: 'OpticalSchool000241', En: 'ResearchExType is not integer.', Cn: '分类参数应为整数' },
    { ID: 'OpticalSchool000243', En: 'This UID ResearchEx does not exist', Cn: '不存在' },
    { ID: 'OpticalSchool000244', En: 'ApplicationUID does not exist.', Cn: '对应Application不存在' },
    { ID: 'OpticalSchool000245', En: 'TechniqueUID does not exist.', Cn: '对应Technique不存在' },
    { ID: 'OpticalSchool000248', En: 'Update Record Error.', Cn: '内部数据错误' },
    { ID: 'OpticalSchool000250', En: 'ResearchExUID is empty', Cn: '参数出错' },
    { ID: 'OpticalSchool000251', En: 'This UID ResearchEx does not exist', Cn: '不存在' },
    { ID: 'OpticalSchool000252', En: 'Delete Record Error.', Cn: '内部数据错误' },
    // 3A PointClaimOther 详情页面,
    { ID: 'Points000051', En: 'PointRequireIndex is not the value of DateTime.', Cn: '排序参数错误' },
    { ID: 'Points000054', En: 'PageSize or PageNumber is not Int type', Cn: '页数及个数错误' },
    { ID: 'Points000055', En: 'PageSize should be over 0.', Cn: '页数及个数错误' },
    // 前台3A PointClaimOtherUpload 详情页面,
    { ID: 'F3APointClaimOtherUpload000001', En: 'Points required Successfully', Cn: '积分请求发送成功' },
    // 3A PointClaimOtherUpload 详情页面,
    { ID: 'Points000010', En: 'Title, Type or Description is empty', Cn: '参数出错' },
    { ID: 'Points000011', En: 'Type is not integer', Cn: '分类参数应为整数' },
    // 前台3A PointClaimOtherInfo 详情页面,
    { ID: 'F3APointClaimOtherInfo000001', En: 'Points requirement updated successful.', Cn: '更新成功' },
    { ID: 'F3APointClaimOtherInfo000002', En: 'Points requirement  deleted successful.', Cn: '删除成功' },
    // 3A PointClaimOtherInfo 详情页面,
    { ID: 'Points000031', En: 'PointRequireUID or Type or Description is empty', Cn: '参数出错' },
    { ID: 'Points000032', En: 'Type is not integer', Cn: '分类参数应为整数' },
    { ID: 'Points000033', En: 'This PointRequireUID does not exist', Cn: '不存在' },
    { ID: 'Points000021', En: 'PointRequireUID is empty', Cn: '参数出错' },
    { ID: 'Points000022', En: 'This PointRequireUID does not exist', Cn: '不存在' },
    { ID: 'Points000041', En: 'PointRequireUID is empty', Cn: '参数出错' },
    { ID: 'Points000042', En: 'This PointRequireUID does not exist', Cn: '不存在' },
    // 3aPointExchange 列出所有礼品
    { ID: 'Gifts000051', En: 'GiftIndex is not the value of DateTime or DateTimeDesc or GiftTitle or GiftTitleDesc.', Cn: '排序参数错误' },
    { ID: 'Gifts000052', En: 'PageSize or PageNumber is not Int type', Cn: '页数及个数错误' },
    { ID: 'Gifts000053', En: 'PageSize should be over 0.', Cn: '页数及个数错误' },
    // 前台3A PointExchangeGiftInfo 详情页面,
    { ID: 'F3APointExchangeGiftInfo000001', En: 'please select $$$$$$', Cn: '请选择$$$$$$' },
    // 3A PointExchangeGiftInfo 详情页面,
    { ID: 'Gifts000040', En: 'GiftUID is empty', Cn: '参数出错' },
    { ID: 'Gifts000041', En: 'the record does not exist.', Cn: '不存在' },
    { ID: 'Gifts000501', En: 'GiftUID, Quantity is empty or Quantity is not integer type.', Cn: '参数出错' },
    { ID: 'Gifts000504', En: 'Quantity should be over than 0.', Cn: '数量需大于0' },
    { ID: 'Gifts000502', En: 'This GiftUID does not exist.', Cn: '不存在' },
    { ID: 'Gifts000503', En: 'your Account Type can not Exchange this Gift.', Cn: '无权限兑换此礼品' },
    // 前台3A PointExchangeGiftCart 详情页面
    { ID: 'F3APointExchangeGiftCart000001', En: 'Your Points is not enough to exchange', Cn: '您的积分不够' },
    { ID: 'F3APointExchangeGiftCart000002', En: 'Gifts exchange submited successfully', Cn: '礼品况换提交成功' },
    // 3A PointExchangeGiftCart 详情页面
    { ID: 'Gifts000511', En: 'GiftInCartUID, Quantity is empty or Quantity is not integer type', Cn: '参数出错' },
    { ID: 'Gifts000512', En: 'This GiftInCartUID is not Exist.', Cn: '不存在' },
    { ID: 'Gifts000531', En: 'NeedDelivery is empty or NeedDelivery is nto bool type', Cn: '参数出错' },
    { ID: 'Gifts000532', En: 'Recipient, Address, Phone, City is empty', Cn: '参数出错' },
    { ID: 'Gifts000533', En: 'the CityUID does not exist.', Cn: '城市不存在' },
    { ID: 'Gifts000534', En: 'Cart is empty, can not order.', Cn: '礼品车空，不能生成兑换订单' },
    { ID: 'Gifts000538', En: 'gift in your cart has been deleted, please delete it, then order.', Cn: '礼品已下架，请重新刷新' },
    { ID: 'Gifts000535', En: 'your Account Type can not Exchange this Gift', Cn: '无权限兑换此礼品' },
    { ID: 'Gifts000536', En: 'This UID User does not exist', Cn: '请重新登陆' },
    { ID: 'Gifts000537', En: 'Your Points is not enough to exchange these gifts.', Cn: '您的积分不够' },
    // 3aPointExchangeBill 列出所有订单
    { ID: 'Gifts000571', En: 'PageSize or PageNumber is not Int type', Cn: '页数及个数错误' },
    { ID: 'Gifts000572', En: 'PageSize should be over 0.', Cn: '页数及个数错误' },
    // 前台3A PointExchangeBillInfo 详情页面
    { ID: 'F3APointExchangeBillInfo000001', En: 'Bill deleted successfully', Cn: '订单删除成功' },
    // 3A PointExchangeBillInfo 详情页面
    { ID: 'Gifts000581', En: 'GiftBillUID is empty', Cn: '参数出错' },
    { ID: 'Gifts000582', En: 'the record does not exist.', Cn: '不存在' },
    { ID: 'Gifts000563', En: 'this status is not 10, can not delete.', Cn: '只有未通过审核订单才能删除' },
    // 3aEquipment 详情页面
    { ID: 'User000401', En: 'You are not Lab account or User account, can not get your purchased products.', Cn: '只有user,Lab帐户才有相关设备' },
    { ID: 'User000406', En: 'This User account Lab UserUID is NULL.', Cn: '没有相关Lab帐号' },
    { ID: 'User000402', En: 'ProductIndex is not the value of ContractDateTime or ContractDateTimeDesc or ProductsName or ProductsNameDesc', Cn: '参数出错' },
    { ID: 'User000403', En: 'PageSize or PageNumber is not Int type', Cn: '页数及个数错误' },
    { ID: 'User000404', En: 'PageSize should be over 0.', Cn: '页数及个数错误' },
    { ID: 'User000405', En: 'Not Result.', Cn: '内部数据错误' },
    // 3aLabUsers 详情页面
    { ID: 'User000271', En: 'You are not Lab account, can not get the your user accounts.', Cn: '只有Lab帐户才有相关Users' },
    { ID: 'User000272', En: 'ClientUserIndex is not the value of DateTime or DateTimeDesc or Account or AccountDesc or Email or EmailDesc  or NickName or NickNameDesc', Cn: '参数出错' },
    { ID: 'User000273', En: 'UserType is not integer.', Cn: 'UserType参数出错' },
    { ID: 'User000275', En: 'Login is not bool type.', Cn: 'Login参数出错' },
    { ID: 'User000276', En: 'PageSize or PageNumber is not Int type', Cn: '页数及个数错误' },
    { ID: 'User000277', En: 'PageSize should be over 0.', Cn: '页数及个数错误' },
    // 前台3A LabUsersInfo 详情页面
    { ID: 'F3ALabUersInfo000001', En: 'Review successfully', Cn: '用户审核完成' },
    // 3A LabUsersInfo 详情页面
    { ID: 'User000291', En: 'You are not Lab account, can not get the your user accounts info.', Cn: '只有Lab帐户才能查看' },
    { ID: 'User000292', En: 'UserUID is empty', Cn: 'UserUID参数出错' },
    { ID: 'User000293', En: 'This UID User does not exist or it is not your user.', Cn: '不存在' },
    // 3A LabReviewItsApplyingUser 详情页面
    { ID: 'User000311', En: 'You are not Lab account, can not review your user.', Cn: '不是Lab帐号' },
    { ID: 'User000312', En: 'UserUID or Status is empty.', Cn: '参数错' },
    { ID: 'User000313', En: 'Status is not integer.', Cn: '参数错' },
    { ID: 'User000314', En: 'Status: 10 for Not Pass; 100 for pass', Cn: '参数错' },
    { ID: 'User000315', En: 'This UID User is not exist or it is not your user.', Cn: '参数错' },
    { ID: 'User000316', En: 'This UID User do not activiate, can not review it.', Cn: '用户未激活' },
    { ID: 'User000317', En: 'Users associated the lab account is full.', Cn: '该实验室账号下关联用户名额已满' },
    { ID: 'User000318', En: 'Review Record Error.', Cn: '系统错误' },
    // 前台3APartner 详情页面
    { ID: 'F3APartner000001', En: 'Only accept jpg/gif/png.', Cn: '仅限jpg, gif, png' },
    { ID: 'F3APartner000002', En: 'The maximum size is 1M.', Cn: '文件请不要超过1M' },
    { ID: 'F3APartner000003', En: 'Applied successfully', Cn: '申请已发送' },
    { ID: 'F3APartner000004', En: 'Updated successfully', Cn: '修改成功' },
    { ID: 'F3APartner000005', En: 'Deleted successfully', Cn: '删除成功' },
    // 3APartner 详情页面
    { ID: 'Opportunity000001', En: 'Company or CityUID or Telephone or Email or Description is empty', Cn: '参数出错' },
    { ID: 'Opportunity000002', En: 'Image is empty', Cn: '请上传一张图片' },
    { ID: 'Opportunity000003', En: 'Image is not Image file', Cn: '上传的文件不是图片' },
    { ID: 'Opportunity000004', En: 'Image size is over 1Mb', Cn: '图片不能超过1M' },
    { ID: 'Opportunity000005', En: 'the UserUID does not exist.', Cn: '用户不存在' },
    { ID: 'Opportunity000006', En: 'the User is not Lab, not allowed the apply.', Cn: '只有Lab才能申请' },
    { ID: 'Opportunity000007', En: 'the User is already Collaboration.', Cn: '已经是合用伙伴了，不要重复申请' },
    { ID: 'Opportunity000008', En: 'the user has applied.', Cn: '已经申请过了，不要重复申请' },
    { ID: 'Opportunity000009', En: 'the CityUID does not exist.', Cn: '城市不对' },
    { ID: 'Opportunity000010', En: 'wrong mail format.', Cn: '邮箱格式不对' },
    { ID: 'Opportunity000021', En: 'Company or CityUID or Telephone or Email or Description is empty', Cn: '参数出错' },
    { ID: 'Opportunity000022', En: 'the record does not exist or the application has been passed, cant update.', Cn: '不存在申请记录，或已被通过，不能修改' },
    { ID: 'Opportunity000023', En: 'Image is not Image file', Cn: '上传的文件不是图片' },
    { ID: 'Opportunity000024', En: 'Image size is over 1Mb', Cn: '图片不能超过1M' },
    { ID: 'Opportunity000025', En: 'the CityUID does not exist.', Cn: '城市不对' },
    { ID: 'Opportunity000026', En: 'wrong mail format.', Cn: '邮箱格式不对' },
    { ID: 'Opportunity000031', En: 'the record does not exist or the application has been passed, can not delete.', Cn: '不存在申请记录，或已被通过，不能删除' },
    // 前台3A PositionCreate 详情页面
    { ID: 'F3APositionCreate000001', En: 'Created a position successfully', Cn: '发布职位成功' },
    // 3A PositionCreate 详情页面
    { ID: 'Opportunity000201', En: 'JobName, Address, Email, CityUID, Telephone, ContactPerson, ExpirationDate, Description, JobType, is empty', Cn: '参数出错' },
    { ID: 'Opportunity000202', En: 'no permission to release Job, only allow Lab', Cn: '只有Lab才能发布职位' },
    { ID: 'Opportunity000203', En: 'wrong mail format.', Cn: '邮箱格式不对' },
    { ID: 'Opportunity000204', En: 'the CityUID does not exist.', Cn: '城市不存在' },
    { ID: 'Opportunity000205', En: 'ExpirationDate is not a date string, format:2012-12-28', Cn: '日期格式出错' },
    // 前台3A PositionInfo 详情页面
    { ID: 'F3APositionInfo000001', En: 'Updated successfully', Cn: '修改成功' },
    { ID: 'F3APositionInfo000002', En: 'deleted successfully', Cn: '删除成功' },
    // 3A PositionInfo 详情页面
    { ID: 'Opportunity000211', En: 'JobName, Address, Email, CityUID, Telephone, ContactPerson, ExpirationDate, Description, JobType, is empty', Cn: '参数出错' },
    { ID: 'Opportunity000212', En: 'no permission to release Job, only allow Lab', Cn: '只有Lab才能发布职位' },
    { ID: 'Opportunity000213', En: 'wrong mail format.', Cn: '邮箱格式不对' },
    { ID: 'Opportunity000214', En: 'the CityUID does not exist.', Cn: '城市不存在' },
    { ID: 'Opportunity000215', En: 'ExpirationDate is not a date string, format:2012-12-28', Cn: '日期格式出错' },
    { ID: 'Opportunity000216', En: 'the record does not exist or the record is not belong to the user.', Cn: '不存在' },
    { ID: 'Opportunity000221', En: '[JobReleaseUID]is empty', Cn: '参数出错' },
    { ID: 'Opportunity000222', En: 'the record does not exist or the record is not belong to the user.', Cn: '无权删除' },
    // 前台3A PositionInfo 详情页面
    { ID: 'FResetPass000001', En: 'Cell verified, please continue to reset password.', Cn: '手机验证成功，请继续修改密码' },
    // resetPass 详情页面
    { ID: 'User000701', En: 'Email is empty', Cn: '参数出错' },
    { ID: 'User000702', En: 'This Email does not exist.', Cn: '邮箱不存在' },
    { ID: 'User000703', En: 'The interval between two times of sending mail should be more than 5 minutes.', Cn: '请间隔5分钟以上重新发送邮件' },
    { ID: 'User000711', En: 'NewPass, CallNumber or CountryCode is empty', Cn: '参数出错' },
    { ID: 'User000712', En: 'Call Number Error.', Cn: '手机号码错误' },
    { ID: 'User000713', En: 'Call Number Error.', Cn: '手机号码错误' },
    { ID: 'User000714', En: 'Call Number is not exist.', Cn: '手机号码不存在' },
    { ID: 'Library000501', Cn: '参数错误' },
    { ID: 'Library000502', Cn: '产品不存在' },
    { ID: 'Library000503', Cn: '用户不存在' }
];